### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by MrYaoShao** [QuintenQVD0/Palword-server-config-parser#1]
How to use

**Comment by QuintenQVD0** [comment]
> How to use

Its prity clear? when you launch it it will look for the configuration file and based on the environment variables that exits with their value change it in the config file

**Comment by MrYaoShao** [comment]
![微信截图_20240208024332](https://github.com/QuintenQVD0/Palword-server-config-parser/assets/51957882/18fdcbaa-9665-4370-a637-ad94ad11bd44)
Look that？
Here's how I configure the variables,
But he doesn't work

**Comment by QuintenQVD0** [comment]
as you put `ALL` and it is `All` ? the parser should have set it just fine in the latest version

**Comment by QuintenQVD0** [comment]
If your parser version is up to date and not the one that default ships with the pterodactyl egg then it will work

![afbeelding](https://github.com/QuintenQVD0/Palword-server-config-parser/assets/67589015/b4e04c1d-6e76-4a14-96c2-0bb71b3dc971)

**Comment by MrYaoShao** [comment]
Could you tell me where the parser needs to be uploaded?

**Comment by xiajunyou** [comment]
![Uploading 微信截图_20240208030148.png…]()

**Comment by MrYaoShao** [comment]
![微信截图_20240208030148](https://github.com/QuintenQVD0/Palword-server-config-parser/assets/51957882/58af1ec6-e99c-4b4f-baa8-cb69c0f6f32f)

**Comment by QuintenQVD0** [comment]
> Could you tell me where the parser needs to be uploaded?

Main directory.

and an empty settings file likely means very old egg as the latest egg handles that just fine

**Comment by MrYaoShao** [comment]
uploaded /
home
/container？

**Comment by MrYaoShao** [comment]
![20240208033146](https://github.com/QuintenQVD0/Palword-server-config-parser/assets/51957882/0052fcd9-8ae4-45e6-98c4-fb02ee825550)

How do I add new variables?
DeathPenalty

**Comment by QuintenQVD0** [comment]
> ![20240208033146](https://private-user-images.githubusercontent.com/51957882/303113366-0052fcd9-8ae4-45e6-98c4-fb02ee825550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMzQ2OTMsIm5iZiI6MTcwNzMzNDM5MywicGF0aCI6Ii81MTk1Nzg4Mi8zMDMxMTMzNjYtMDA1MmZjZDktOGFlNC00NWU2LTk4YzQtZmIwMmVlODI1NTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE5MzMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMGJmOTM2OWNlOGU3MTAzYTNiYmQ4ZjY2NTY2Njg3NmE5MTE0M2E1M2Y5OWQxZTdkZmIyMWMxMGQ2OGU1YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.El0FxXFCJ-NnBNz5C1rOmfUQKLKbaca74TyaExAMbAw)
> 
> How do I add new variables? DeathPenalty

currently with the offical egg not. expect if you replace the binary.

**Comment by QuintenQVD0** [comment]
![afbeelding](https://github.com/QuintenQVD0/Palword-server-config-parser/assets/67589015/57c4c867-7da3-42fb-9abf-87aba25be9b3)
Then hit reinstall

**Comment by MrYaoShao** [comment]
yes！ i replace the binary.

**Comment by MrYaoShao** [comment]
I replaced the binary file
Now how do I configure the variables
DEATH_PENALTY

**Comment by QuintenQVD0** [comment]
> I replaced the binary file Now how do I configure the variables DEATH_PENALTY

just like you did as it it does that for me?

**Comment by MrYaoShao** [comment]
Yes, but it doesn't work

**Comment by QuintenQVD0** [comment]
> Yes, but it doesn't work

With does not work I am nothing, you are going to have to be a bit more specific.

**Comment by MrYaoShao** [comment]
![1111](https://github.com/QuintenQVD0/Palword-server-config-parser/assets/51957882/3e382bfd-5aaf-44a9-95a2-c55db7bd033a)
![1345](https://github.com/QuintenQVD0/Palword-server-config-parser/assets/51957882/2536ee4b-ca8c-44cf-abce-4eb5d317d7c9)
Look that

**Comment by QuintenQVD0** [comment]
> ![1111](https://private-user-images.githubusercontent.com/51957882/303124246-3e382bfd-5aaf-44a9-95a2-c55db7bd033a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNDAwNjUsIm5iZiI6MTcwNzMzOTc2NSwicGF0aCI6Ii81MTk1Nzg4Mi8zMDMxMjQyNDYtM2UzODJiZmQtNWFhZi00NGE5LTk1YTItYzU1ZGI3YmQwMzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDIxMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MGExZmQyNDU2MDgwNGVhZGM5YmI1MTM3MmYwNjE5M2NiY2Y2YTEzMzVhMjIyMWMzMTk0Y2VlNTIyMWI1YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9yvsmuJ_mQAIJNKtdQc50kXwjYk-WmlNGjQTXfFtk4s) ![1345](https://private-user-images.githubusercontent.com/51957882/303124298-2536ee4b-ca8c-44cf-abce-4eb5d317d7c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNDAwNjUsIm5iZiI6MTcwNzMzOTc2NSwicGF0aCI6Ii81MTk1Nzg4Mi8zMDMxMjQyOTgtMjUzNmVlNGItY2E4Yy00NGNmLWFiY2UtNGViNWQzMTdkN2M5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDIxMDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNzFiZThlMDJjZjg2NzdkMjVhYjE1YmZjOTU4ODQwOTdlZTk0YzBkOGIyMzIzNzA3NTZkNTY3NGI3NWU2MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iLa5ZlmmZEvXBl-_kfMMRZWa4FDCOpyacNYd6nZGnrs) Look that

I will re-test it myself and report back as it did work for me.

**Comment by MrYaoShao** [comment]
No validation rule specified for key: AutoResetGuildTimeNoOnlinePlayers
Updating key: AutoResetGuildTimeNoOnlinePlayers with value: 72.000000
No validation rule specified for key: bIsStartLocationSelectByMap
Validation failed for key: bAutoResetGuildNoOnlinePlayers, value: False
Validation failed for key: DropItemAliveMaxHours, value: 1.000000
No validation rule specified for key: PalAutoHPRegeneRate

These are some variables that report errors

**Comment by QuintenQVD0** [comment]
> No validation rule specified for key: AutoResetGuildTimeNoOnlinePlayers Updating key: AutoResetGuildTimeNoOnlinePlayers with value: 72.000000 No validation rule specified for key: bIsStartLocationSelectByMap Validation failed for key: bAutoResetGuildNoOnlinePlayers, value: False Validation failed for key: DropItemAliveMaxHours, value: 1.000000 No validation rule specified for key: PalAutoHPRegeneRate
> 
> These are some variables that report errors

Now you are running a dev release. So that is expected.

**Comment by QuintenQVD0** [comment]
@MrYaoShao Please repull the latest pre-release, all validation should be fixt

**Comment by MrYaoShao** [comment]
OK, I'll give it a try

**Comment by MrYaoShao** [comment]
Everything is OK！ good job！
