### ISSUE TITLE
What am i missing how do i use this? Sorry if im missing something. 

### ISSUE THREAD

**Issue by exrith** [QuintenQVD0/Palword-server-config-parser#10]
How do i install the [Palworld-Config-Parser-Tool] and use it with a palworld server? 

Is it a egg i run along side the palworld egg, a tool i install inside the egg? I'm just missing the documentation or just not getting something key here.

**Comment by QuintenQVD0** [comment]
> How do i install the [Palworld-Config-Parser-Tool] and use it with a palworld server?
> 
> Is it a egg i run along side the palworld egg, a tool i install inside the egg? I'm just missing the documentation or just not getting something key here.

It is an application that can parse the palworld config based on env variables. If you use pelican or ptero then this is automatically used in the eggs.

**Comment by exrith** [comment]
So I don't have to install it then? I am using a pelican egg for palworld. 

Maybe I'm misunderstanding the use, but I thought it would allow my to edit the server setting like pal spawn count for example, and that would be able to be changed in the startup or settings tab.

**Comment by QuintenQVD0** [comment]
> So I don't have to install it then? I am using a pelican egg for palworld.
> 
> Maybe I'm misunderstanding the use, but I thought it would allow my to edit the server setting like pal spawn count for example, and that would be able to be changed in the startup or settings tab.

For that you must modify the egg. Add the right variables to it and the parser will pick them up and replace them in the config. Some basic ones are already in the egg.

**Comment by QuintenQVD0** [comment]
Closing this as it is stale, if you still have questions then feel free to make a comment.
