### ISSUE TITLE
Add parameter directyle to the command

### ISSUE THREAD

**Issue by MrBretze** [QuintenQVD0/Palword-server-config-parser#2]
Hello, it's possible to add a config key to the command args directly like 

`./PalworldServerConfigParser -BUILD_OBJECT_DETERIORATION_DAMAGE_RATE=0.00000 -DEATH_PENALTY=NONE -EXP_RATE=5` 

Because it's not very user-friendly to add a variable to the pterodactyl eggs for every parameter

Regards, MrBretzel.

**Comment by QuintenQVD0** [comment]
> Hello, it's possible to add a config key to the command args directly like
> 
> `./PalworldServerConfigParser -BUILD_OBJECT_DETERIORATION_DAMAGE_RATE=0.00000 -DEATH_PENALTY=NONE -EXP_RATE=5`
> 
> Because it's not very user-friendly to add a variable to the pterodactyl eggs for every parameter
> 
> Regards, MrBretzel.

It would still need all variables to be added for pterodactyl the be able to change them. 
And there is no need to add them all. if a variable does not exitis the parser will just skip over them and not touch the value

**Comment by QuintenQVD0** [comment]
> Hello, it's possible to add a config key to the command args directly like
> 
> `./PalworldServerConfigParser -BUILD_OBJECT_DETERIORATION_DAMAGE_RATE=0.00000 -DEATH_PENALTY=NONE -EXP_RATE=5`
> 
> Because it's not very user-friendly to add a variable to the pterodactyl eggs for every parameter
> 
> Regards, MrBretzel.

To be honest it is way cleaner as else the startup command will be huge, and you would still need a variable for every thing that should be changeable. as it still would be ` -BUILD_OBJECT_DETERIORATION_DAMAGE_RATE={{VARIABLE}}`

But ENV variables that not exitis will not be parsed, so its up to yourself to change / add the ones you want to be able to be parsed / changed.

**Comment by QuintenQVD0** [comment]
I could do it but I personally find that not needed

**Comment by MrBretze** [comment]
> But ENV variables that not exitis will not be parsed, so its up to yourself to change / add the ones you want to be able to be parsed / changed.

Oh okay, I didn't know it sorry

**Comment by QuintenQVD0** [comment]
https://github.com/QuintenQVD0/Palword-server-config-parser/blob/main/main.go#L263-L270

if you were interested, this is the logic that will be false (the ok variable) if the variable does not exits and then just skip
