### ISSUE TITLE
ENV Change not taking affect

### ISSUE THREAD

**Issue by Shybella** [QuintenQVD0/Palword-server-config-parser#8]
I added a variable for `ALLOW_CONNECT_PLATFORM`

```
        {
            "name": "Network Provider",
            "description": "Change between Steam and Xbox providers",
            "env_variable": "ALLOW_CONNECT_PLATFORM",
            "default_value": "Xbox",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|string",
            "field_type": "text"
        }
```

However, this change does not seem to be taking place. Am I misunderstanding something? The `AllowConnectPlatform=Steam` remains `Steam`

Thank you!

**Comment by Shybella** [comment]
Follow up, is this related to #1 

Do I need to change `https:\/\/raw.githubusercontent.com\/parkervcp\/eggs\/master\/game_eggs\/steamcmd_servers\/palworld\/PalworldServerConfigParser-linux-amd64`

to
`https://github.com/QuintenQVD0/Palword-server-config-parser/releases/download/v1.0.13/PalworldServerConfigParser-linux-amd64`

**Comment by Shybella** [comment]
Yes, that was the issue. Resolved.

**Comment by QuintenQVD0** [comment]
Nice to hear that it was resolved. If it does not work then thats probly because the parser does know that variable yet.

**Comment by Shybella** [comment]
Thanks for the response, this tool is really cool. Thanks for spending the time making it
